# Generated by Django 4.0.5 on 2023-05-08 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='General_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to='images/')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=100)),
                ('contact_num', models.CharField(max_length=30, null=True)),
                ('e_mail', models.EmailField(max_length=50)),
                ('birth_date', models.DateField()),
                ('location', models.CharField(max_length=50)),
                ('summary', models.TextField(max_length=1000, null=True)),
                ('programming', models.TextField(max_length=1000, null=True)),
                ('tools', models.TextField(max_length=1000, null=True)),
                ('techniques', models.TextField(max_length=1000, null=True)),
                ('certification', models.TextField(max_length=1000, null=True)),
            ],
            options={
                'verbose_name_plural': 'General info',
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('job_location', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(null=True)),
                ('in_job_experience', models.TextField(max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': 'Jobs',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('heading', models.CharField(max_length=100)),
                ('subheading', models.CharField(blank=True, max_length=100, null=True)),
                ('summary', models.CharField(blank=True, max_length=200, null=True)),
                ('project_type', models.CharField(blank=True, choices=[('live', 'live'), ('informational', 'informational')], max_length=250, null=True)),
                ('src_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('post', models.TextField(blank=True, max_length=10000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_experience', models.TextField(max_length=800, null=True)),
                ('company_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.jobs')),
            ],
            options={
                'verbose_name_plural': 'Experience',
            },
        ),
    ]
