# Generated by Django 4.0.5 on 2022-08-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='job_experience',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
