# Generated by Django 4.0.5 on 2022-08-04 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='general_info',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='job_experience',
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_experience', models.TextField(max_length=800, null=True)),
                ('company_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.jobs')),
            ],
            options={
                'verbose_name_plural': 'Experience',
            },
        ),
    ]
