# Generated by Django 4.0.5 on 2022-08-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_jobs_general_info_remove_jobs_job_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='in_job_experience',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
