# Generated by Django 4.0.5 on 2022-08-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_general_info_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='post',
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
