# Generated by Django 4.0.5 on 2022-08-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_project_post_alter_project_subheading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='src_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
