# Generated by Django 4.0.5 on 2022-08-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_project_src_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='src_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
