# Generated by Django 4.1 on 2022-08-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_project_src_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(blank=True, choices=[('live', 'live'), ('informational', 'informational')], max_length=250, null=True),
        ),
    ]
